apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:  
        - containerPort: 80
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: postgres-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:  
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "PASSWORD"