# certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: krishdev-tech-cert
  namespace: default
spec:
  secretName: krishdev-tech-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: krishdev.tech
  dnsNames:
  - krishdev.tech
  - www.krishdev.tech
